### ISSUE TITLE
BUG Report: `CreateBitmapFromMemory` Method Fails in Vortice.Direct2D1 version 3.6.2

### ISSUE THREAD

**Issue by sdcb** [amerkoleci/Vortice.Windows#474] opened 2024-12-16 07:05 UTC
#### Description

After updating from version 3.5.0 to 3.6.2 of `Vortice.Direct2D1`, the `CreateBitmapFromMemory` method fails to execute and throws the following exception:

```
Message: The type initializer for '<Module>' threw an exception.

InnerException:
MissingMethodException: Method not found: 'Void WinRT.ComWrappersSupport.RegisterTypeComInterfaceEntriesLookup(System.Func`2<System.Type,ComInterfaceEntry[]>)'.

StackTrace:
   at Vortice.WIC.PixelFormat..cctor()
   at UserQuery.Main(), line 6

Data: (0 items)
HelpLink: null
HResult: -2146233036
Source: Vortice.Direct2D1
TargetSite: System.Reflection.MethodBase
TypeName: <Module>
```

#### Steps to Reproduce

1. Create a new .NET project.
2. Reference version 3.6.2 of `Vortice.Direct2D1`.
3. Use the following code to attempt to create a bitmap:

   ```csharp
   using IWICImagingFactory2 wic = new();
   using ID2D1Factory d2dFac = D2D1.D2D1CreateFactory<ID2D1Factory>();
   var data = new byte[640 * 480 * 4];
   fixed (byte* ptr = data)
   {
       using IWICBitmap bmp = wic.CreateBitmapFromMemory(640, 480, PixelFormat.Format32bppPBGRA, (nint)ptr);
   }
   ```

4. Run the program and observe the exception.

#### Expected Behavior

The code runs successfully as it did in version 3.5.0, and the behavior should remain consistent in version 3.6.2.

#### Actual Behavior

The code throws a `MissingMethodException` in version 3.6.2.

#### Possible Cause

It was noted that the parameters `Width` and `Height` have changed from `int` to `uint` in version 3.6.2. This change might be related to the issue, but there could be a deeper issue related to modifications in the project's interface or method calls, especially concerning the `WinRT.ComWrappersSupport.RegisterTypeComInterfaceEntriesLookup` method.

#### Environment

- Operating System: Windows 11
- .NET Core/Framework Version: .NET 9
- Vortice.Direct2D1 Version: 3.6.2

**Comment by sdcb** [comment] 2024-12-16 07:07
Note, I'm running above code in LINQPad 8, not sure it's related to LINQPad or not.

**Comment by amerkoleci** [comment] 2024-12-16 07:40
Probably you have mixed vortice versions, make sure all your dependencies are correctly updated

**Comment by amerkoleci** [comment] 2024-12-16 07:48
Hi,
I've just with Visual Studio 2022 and Console application and it doesn't happen.
Please share a repro test case.

Thanks!

**Comment by sdcb** [comment] 2024-12-16 07:50
> Probably you have mixed vortice versions, make sure all your dependencies are correctly updated

No I didn't mix vortices versions, so it's most likely related by LINQPad 8:

This is the source code:

```linq
<Query Kind="Statements">
  <NuGetReference>Vortice.Direct2D1</NuGetReference>
  <Namespace>Vortice.Direct2D1</Namespace>
  <Namespace>Vortice.WIC</Namespace>
</Query>

using IWICImagingFactory2 wic = new();
using ID2D1Factory d2dFac = D2D1.D2D1CreateFactory<ID2D1Factory>();
var data = new byte[640 * 480 * 4];
fixed (byte* ptr = data)
{
	using IWICBitmap bmp = wic.CreateBitmapFromMemory(640, 480, PixelFormat.Format32bppPBGRA, (nint)ptr);
}
```

**Comment by sdcb** [comment] 2024-12-16 08:01
I posted in link here: https://forum.linqpad.net/discussion/3304/bug-report-createbitmapfrommemory-exception-in-linqpad-8-with-vortice-direct2d1-version-3-6-2/p1?new=1

**Comment by albahari** [comment] 2024-12-19 06:26
This is now fixed in the latest LINQPad 8 beta. The issue was caused by LINQPad importing an older WinSDK version.

**Closed** 2024-12-19 06:27 UTC
